# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalculadoraPy.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculadora(object):
    def setupUi(self, Calculadora):
        
        Calculadora.setObjectName("Calculadora")
        Calculadora.resize(400, 600)
        Calculadora.setMinimumSize(QtCore.QSize(400, 600))
        Calculadora.setMaximumSize(QtCore.QSize(400, 600))
        Calculadora.setStyleSheet("QWidget{\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.Top = QtWidgets.QFrame(Calculadora)
        self.Top.setGeometry(QtCore.QRect(10, 10, 381, 131))
        self.Top.setStyleSheet("QFrame{\n"
"background-color: rgb(15, 15, 15);\n"
"}\n"
"")
        self.Top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top.setObjectName("Top")
        self.LastDisplay = QtWidgets.QFrame(self.Top)
        self.LastDisplay.setGeometry(QtCore.QRect(20, 40, 341, 80))
        self.LastDisplay.setStyleSheet("background-color: rgb(25,25,25);")
        self.LastDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LastDisplay.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LastDisplay.setObjectName("LastDisplay")
        self.Display = QtWidgets.QLabel(self.LastDisplay)
        self.Display.setEnabled(True)
        self.Display.setGeometry(QtCore.QRect(16, 10, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.Display.setFont(font)
        self.Display.setStyleSheet("QLabel{\n"
"    border: 0.5px solid rgb(70,70,70);\n"
"    background-color: rgb(0, 170, 127);\n"
"}")
        self.Display.setText("")
        self.Display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Display.setObjectName("Display")
        self.Marca = QtWidgets.QLabel(self.Top)
        self.Marca.setGeometry(QtCore.QRect(20, 0, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Demi ITC")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Marca.setFont(font)
        self.Marca.setStyleSheet("color: rgb(255, 255, 255);")
        self.Marca.setObjectName("Marca")
        self.Modelo = QtWidgets.QLabel(self.Top)
        self.Modelo.setGeometry(QtCore.QRect(300, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Modelo.setFont(font)
        self.Modelo.setStyleSheet("color: rgb(255, 255, 255);")
        self.Modelo.setObjectName("Modelo")
        self.Bot = QtWidgets.QFrame(Calculadora)
        self.Bot.setGeometry(QtCore.QRect(10, 150, 381, 441))
        self.Bot.setStyleSheet("background-color: rgb(15, 15, 15);")
        self.Bot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Bot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bot.setObjectName("Bot")
        self.BtnDEL = QtWidgets.QPushButton(self.Bot)
        self.BtnDEL.setGeometry(QtCore.QRect(10, 20, 57, 40))
        self.BtnDEL.setStyleSheet("QPushButton {\n"
"background-color: rgb(11, 137, 255);\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(1, 111, 255);\n"
"}")
        self.BtnDEL.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/DEL_AC/DEL.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnDEL.setIcon(icon)
        self.BtnDEL.setIconSize(QtCore.QSize(30, 40))
        self.BtnDEL.setObjectName("BtnDEL")
        self.BtnAC = QtWidgets.QPushButton(self.Bot)
        self.BtnAC.setGeometry(QtCore.QRect(80, 20, 57, 40))
        self.BtnAC.setStyleSheet("QPushButton {\n"
"background-color: rgb(255, 88, 88);\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(255, 43, 43);\n"
"}")
        self.BtnAC.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/DEL_AC/AC.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnAC.setIcon(icon1)
        self.BtnAC.setIconSize(QtCore.QSize(30, 40))
        self.BtnAC.setObjectName("BtnAC")
        self.BtnON = QtWidgets.QPushButton(self.Bot)
        self.BtnON.setGeometry(QtCore.QRect(240, 20, 57, 40))
        self.BtnON.setStyleSheet("QPushButton {\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(35, 35, 35);\n"
"}")
        self.BtnON.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/ON_OFF/Encendido.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnON.setIcon(icon2)
        self.BtnON.setIconSize(QtCore.QSize(30, 40))
        self.BtnON.setObjectName("BtnON")
        self.BtnOFF = QtWidgets.QPushButton(self.Bot)
        self.BtnOFF.setGeometry(QtCore.QRect(310, 20, 57, 40))
        self.BtnOFF.setStyleSheet("QPushButton {\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(35, 35, 35);\n"
"}")
        self.BtnOFF.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/ON_OFF/Apagado.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnOFF.setIcon(icon3)
        self.BtnOFF.setIconSize(QtCore.QSize(30, 40))
        self.BtnOFF.setObjectName("BtnOFF")
        self.BtnLn = QtWidgets.QPushButton(self.Bot)
        self.BtnLn.setGeometry(QtCore.QRect(50, 90, 65, 40))
        self.BtnLn.setStyleSheet("QPushButton {\n"
"background-color: rgb(170,170,170);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(120,120, 120);\n"
"}")
        self.BtnLn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Operadores/Logaritmo_natural.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnLn.setIcon(icon4)
        self.BtnLn.setIconSize(QtCore.QSize(35, 40))
        self.BtnLn.setObjectName("BtnLn")
        self.BtnLog = QtWidgets.QPushButton(self.Bot)
        self.BtnLog.setGeometry(QtCore.QRect(120, 90, 65, 40))
        self.BtnLog.setStyleSheet("QPushButton {\n"
"background-color: rgb(170,170,170);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(120,120, 120);\n"
"}")
        self.BtnLog.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Operadores/Logaritmo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnLog.setIcon(icon5)
        self.BtnLog.setIconSize(QtCore.QSize(35, 40))
        self.BtnLog.setObjectName("BtnLog")
        self.BtnExp2 = QtWidgets.QPushButton(self.Bot)
        self.BtnExp2.setGeometry(QtCore.QRect(190, 90, 65, 40))
        self.BtnExp2.setStyleSheet("QPushButton {\n"
"background-color: rgb(170,170,170);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(120,120, 120);\n"
"}")
        self.BtnExp2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Operadores/Potencia_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnExp2.setIcon(icon6)
        self.BtnExp2.setIconSize(QtCore.QSize(35, 40))
        self.BtnExp2.setObjectName("BtnExp2")
        self.BtnExp3 = QtWidgets.QPushButton(self.Bot)
        self.BtnExp3.setGeometry(QtCore.QRect(260, 90, 65, 40))
        self.BtnExp3.setStyleSheet("QPushButton {\n"
"background-color: rgb(170,170,170);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(120,120, 120);\n"
"}")
        self.BtnExp3.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Operadores/Potencia_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnExp3.setIcon(icon7)
        self.BtnExp3.setIconSize(QtCore.QSize(35, 40))
        self.BtnExp3.setObjectName("BtnExp3")
        self.BtnParDer = QtWidgets.QPushButton(self.Bot)
        self.BtnParDer.setGeometry(QtCore.QRect(260, 140, 65, 40))
        self.BtnParDer.setStyleSheet("QPushButton {\n"
"background-color: rgb(170,170,170);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(120,120, 120);\n"
"}")
        self.BtnParDer.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Operadores/ParDer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnParDer.setIcon(icon8)
        self.BtnParDer.setIconSize(QtCore.QSize(35, 40))
        self.BtnParDer.setObjectName("BtnParDer")
        self.BtnPorc = QtWidgets.QPushButton(self.Bot)
        self.BtnPorc.setGeometry(QtCore.QRect(50, 140, 65, 40))
        self.BtnPorc.setStyleSheet("QPushButton {\n"
"background-color: rgb(170,170,170);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(120,120, 120);\n"
"}")
        self.BtnPorc.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Operadores/Porcentaje.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnPorc.setIcon(icon9)
        self.BtnPorc.setIconSize(QtCore.QSize(35, 40))
        self.BtnPorc.setObjectName("BtnPorc")
        self.BtnParIzq = QtWidgets.QPushButton(self.Bot)
        self.BtnParIzq.setGeometry(QtCore.QRect(190, 140, 65, 40))
        self.BtnParIzq.setStyleSheet("QPushButton {\n"
"background-color: rgb(170,170,170);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(120,120, 120);\n"
"}")
        self.BtnParIzq.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Operadores/ParIz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnParIzq.setIcon(icon10)
        self.BtnParIzq.setIconSize(QtCore.QSize(35, 40))
        self.BtnParIzq.setObjectName("BtnParIzq")
        self.BtnFact = QtWidgets.QPushButton(self.Bot)
        self.BtnFact.setGeometry(QtCore.QRect(120, 140, 65, 40))
        self.BtnFact.setStyleSheet("QPushButton {\n"
"background-color: rgb(170,170,170);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(120,120, 120);\n"
"}")
        self.BtnFact.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Operadores/Factorial.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnFact.setIcon(icon11)
        self.BtnFact.setIconSize(QtCore.QSize(35, 40))
        self.BtnFact.setObjectName("BtnFact")
        self.Btn8 = QtWidgets.QPushButton(self.Bot)
        self.Btn8.setGeometry(QtCore.QRect(120, 210, 65, 40))
        self.Btn8.setStyleSheet("QPushButton {\n"
"background-color: rgb(130,130,130);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(90,90, 90);\n"
"}\n"
"")
        self.Btn8.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Números/8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn8.setIcon(icon12)
        self.Btn8.setIconSize(QtCore.QSize(35, 40))
        self.Btn8.setObjectName("Btn8")
        self.Btn7 = QtWidgets.QPushButton(self.Bot)
        self.Btn7.setGeometry(QtCore.QRect(50, 210, 65, 40))
        self.Btn7.setStyleSheet("QPushButton {\n"
"background-color: rgb(130,130,130);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(90,90, 90);\n"
"}")
        self.Btn7.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Números/7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn7.setIcon(icon13)
        self.Btn7.setIconSize(QtCore.QSize(35, 40))
        self.Btn7.setObjectName("Btn7")
        self.Btn9 = QtWidgets.QPushButton(self.Bot)
        self.Btn9.setGeometry(QtCore.QRect(190, 210, 65, 40))
        self.Btn9.setStyleSheet("QPushButton {\n"
"background-color: rgb(130,130,130);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(90,90, 90);\n"
"}")
        self.Btn9.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Números/9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn9.setIcon(icon14)
        self.Btn9.setIconSize(QtCore.QSize(35, 40))
        self.Btn9.setObjectName("Btn9")
        self.BtnSum = QtWidgets.QPushButton(self.Bot)
        self.BtnSum.setGeometry(QtCore.QRect(260, 210, 65, 40))
        self.BtnSum.setStyleSheet("QPushButton {\n"
"background-color: rgb(170, 170, 170);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(120,120, 120);\n"
"}")
        self.BtnSum.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Operadores/Suma.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnSum.setIcon(icon15)
        self.BtnSum.setIconSize(QtCore.QSize(35, 40))
        self.BtnSum.setObjectName("BtnSum")
        self.Btn5 = QtWidgets.QPushButton(self.Bot)
        self.Btn5.setGeometry(QtCore.QRect(120, 260, 65, 40))
        self.Btn5.setStyleSheet("QPushButton {\n"
"background-color: rgb(130,130,130);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(90,90, 90);\n"
"}")
        self.Btn5.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Números/5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn5.setIcon(icon16)
        self.Btn5.setIconSize(QtCore.QSize(35, 40))
        self.Btn5.setObjectName("Btn5")
        self.Btn4 = QtWidgets.QPushButton(self.Bot)
        self.Btn4.setGeometry(QtCore.QRect(50, 260, 65, 40))
        self.Btn4.setStyleSheet("QPushButton {\n"
"background-color: rgb(130,130,130);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(90,90, 90);\n"
"}")
        self.Btn4.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Números/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn4.setIcon(icon17)
        self.Btn4.setIconSize(QtCore.QSize(35, 40))
        self.Btn4.setObjectName("Btn4")
        self.Btn6 = QtWidgets.QPushButton(self.Bot)
        self.Btn6.setGeometry(QtCore.QRect(190, 260, 65, 40))
        self.Btn6.setStyleSheet("QPushButton {\n"
"background-color: rgb(130,130,130);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(90,90, 90);\n"
"}")
        self.Btn6.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Números/6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn6.setIcon(icon18)
        self.Btn6.setIconSize(QtCore.QSize(35, 40))
        self.Btn6.setObjectName("Btn6")
        self.BtnRes = QtWidgets.QPushButton(self.Bot)
        self.BtnRes.setGeometry(QtCore.QRect(260, 260, 65, 40))
        self.BtnRes.setStyleSheet("QPushButton {\n"
"background-color: rgb(170,170,170);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(120,120, 120);\n"
"}")
        self.BtnRes.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Operadores/Resta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnRes.setIcon(icon19)
        self.BtnRes.setIconSize(QtCore.QSize(35, 40))
        self.BtnRes.setObjectName("BtnRes")
        self.Btn2 = QtWidgets.QPushButton(self.Bot)
        self.Btn2.setGeometry(QtCore.QRect(120, 310, 65, 40))
        self.Btn2.setStyleSheet("QPushButton {\n"
"background-color: rgb(130,130,130);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(90,90, 90);\n"
"}")
        self.Btn2.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Números/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn2.setIcon(icon20)
        self.Btn2.setIconSize(QtCore.QSize(35, 40))
        self.Btn2.setObjectName("Btn2")
        self.Btn1 = QtWidgets.QPushButton(self.Bot)
        self.Btn1.setGeometry(QtCore.QRect(50, 310, 65, 40))
        self.Btn1.setStyleSheet("QPushButton {\n"
"background-color: rgb(130,130,130);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(90,90, 90);\n"
"}")
        self.Btn1.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Números/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn1.setIcon(icon21)
        self.Btn1.setIconSize(QtCore.QSize(35, 40))
        self.Btn1.setObjectName("Btn1")
        self.Btn3 = QtWidgets.QPushButton(self.Bot)
        self.Btn3.setGeometry(QtCore.QRect(190, 310, 65, 40))
        self.Btn3.setStyleSheet("QPushButton {\n"
"background-color: rgb(130,130,130);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(90,90, 90);\n"
"}")
        self.Btn3.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Números/3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn3.setIcon(icon22)
        self.Btn3.setIconSize(QtCore.QSize(35, 40))
        self.Btn3.setObjectName("Btn3")
        self.BtnMult = QtWidgets.QPushButton(self.Bot)
        self.BtnMult.setGeometry(QtCore.QRect(260, 310, 65, 40))
        self.BtnMult.setStyleSheet("QPushButton {\n"
"background-color: rgb(170,170,170);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(120,120, 120);\n"
"}")
        self.BtnMult.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Operadores/Mutiplicación.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnMult.setIcon(icon23)
        self.BtnMult.setIconSize(QtCore.QSize(35, 40))
        self.BtnMult.setObjectName("BtnMult")
        self.BtnPunto = QtWidgets.QPushButton(self.Bot)
        self.BtnPunto.setGeometry(QtCore.QRect(120, 360, 65, 40))
        self.BtnPunto.setStyleSheet("QPushButton {\n"
"background-color: rgb(170,170,170);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(120,120, 120);\n"
"}")
        self.BtnPunto.setText("")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Operadores/Punto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnPunto.setIcon(icon24)
        self.BtnPunto.setIconSize(QtCore.QSize(20, 20))
        self.BtnPunto.setObjectName("BtnPunto")
        self.Btn0 = QtWidgets.QPushButton(self.Bot)
        self.Btn0.setGeometry(QtCore.QRect(50, 360, 65, 40))
        self.Btn0.setStyleSheet("QPushButton {\n"
"background-color: rgb(130,130,130);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(90,90, 90);\n"
"}")
        self.Btn0.setText("")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Números/0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn0.setIcon(icon25)
        self.Btn0.setIconSize(QtCore.QSize(35, 40))
        self.Btn0.setObjectName("Btn0")
        self.BtnDiv = QtWidgets.QPushButton(self.Bot)
        self.BtnDiv.setGeometry(QtCore.QRect(190, 360, 65, 40))
        self.BtnDiv.setStyleSheet("QPushButton {\n"
"background-color: rgb(170,170,170);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(120,120, 120);\n"
"}")
        self.BtnDiv.setText("")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Operadores/Dividir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnDiv.setIcon(icon26)
        self.BtnDiv.setIconSize(QtCore.QSize(35, 40))
        self.BtnDiv.setObjectName("BtnDiv")
        self.BtnResultado = QtWidgets.QPushButton(self.Bot)
        self.BtnResultado.setGeometry(QtCore.QRect(260, 360, 65, 40))
        self.BtnResultado.setStyleSheet("QPushButton {\n"
"background-color: rgb(170, 170, 255);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(170, 85, 255);\n"
"}")
        self.BtnResultado.setText("")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap("Calculadora Python/Iconos/Operadores/Igual.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnResultado.setIcon(icon27)
        self.BtnResultado.setIconSize(QtCore.QSize(20, 35))
        self.BtnResultado.setObjectName("BtnResultado")
        self.Separador1 = QtWidgets.QFrame(self.Bot)
        self.Separador1.setGeometry(QtCore.QRect(-3, 70, 391, 20))
        self.Separador1.setStyleSheet("")
        self.Separador1.setFrameShape(QtWidgets.QFrame.HLine)
        self.Separador1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Separador1.setObjectName("Separador1")
        self.Separador2 = QtWidgets.QFrame(self.Bot)
        self.Separador2.setGeometry(QtCore.QRect(0, 190, 381, 20))
        self.Separador2.setStyleSheet("")
        self.Separador2.setFrameShape(QtWidgets.QFrame.HLine)
        self.Separador2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Separador2.setObjectName("Separador2")
        self.Separador3 = QtWidgets.QFrame(self.Bot)
        self.Separador3.setGeometry(QtCore.QRect(0, 410, 381, 20))
        self.Separador3.setStyleSheet("")
        self.Separador3.setFrameShape(QtWidgets.QFrame.HLine)
        self.Separador3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Separador3.setObjectName("Separador3")
        
        #Números
        self.Btn0.clicked.connect(self.BTN0)
        self.Btn1.clicked.connect(self.BTN1)
        self.Btn2.clicked.connect(self.BTN2)
        self.Btn3.clicked.connect(self.BTN3)
        self.Btn4.clicked.connect(self.BTN4)
        self.Btn5.clicked.connect(self.BTN5)
        self.Btn6.clicked.connect(self.BTN6)
        self.Btn7.clicked.connect(self.BTN7)
        self.Btn8.clicked.connect(self.BTN8)
        self.Btn9.clicked.connect(self.BTN9)
        
        #Operadores
        self.BtnSum.clicked.connect(self.SUMA)
        self.BtnRes.clicked.connect(self.RESTA)
        self.BtnDiv.clicked.connect(self.DIVI)
        self.BtnMult.clicked.connect(self.MULTI)
        self.BtnPunto.clicked.connect(self.PUNTO)
        self.BtnParIzq.clicked.connect(self.PARIZ)
        self.BtnParDer.clicked.connect(self.PARDER)
        self.BtnPorc.clicked.connect(self.PORC)
        self.BtnPunto.clicked.connect(self.PUNTO)
        self.BtnExp2.clicked.connect(self.EXP2)
        self.BtnExp3.clicked.connect(self.EXP3)
        self.BtnFact.clicked.connect(self.FACT)
        self.BtnLn.clicked.connect(self.LN)
        self.BtnLog.clicked.connect(self.LOG)
        
        #ON/OFF
        self.BtnOFF.clicked.connect(self.OFF)
        
        #RESULTADO
        self.BtnResultado.clicked.connect(self.RESULTADO)
        
        #DEL/AC
        self.BtnDEL.clicked.connect(self.DEL)
        self.BtnAC.clicked.connect(self.AC)
        
        self.retranslateUi(Calculadora)
        QtCore.QMetaObject.connectSlotsByName(Calculadora)
    
    #Funciones para la acción de los botones
    def BTN0(self):
        self.update_display('0')
    def BTN1(self):
        self.update_display('1')
    def BTN2(self):
        self.update_display('2')
    def BTN3(self):
        self.update_display('3')
    def BTN4(self):
        self.update_display('4')
    def BTN5(self):
        self.update_display('5')
    def BTN6(self):
        self.update_display('6')
    def BTN7(self):
        self.update_display('7')
    def BTN8(self):
        self.update_display('8')
    def BTN9(self):
        self.update_display('9')
    def SUMA(self):
        self.update_display('+')
    def RESTA(self):
        self.update_display('-')
    def DIVI(self):
        self.update_display('/')
    def MULTI(self):
        self.update_display('*')
    def PUNTO(self):
        self.update_display('.')
    def PARIZ(self):
        self.update_display('(')
    def PARDER(self):
        self.update_display(')')
    def PORC(self):
        self.update_display('%')
    def EXP2(self):
        self.update_display('^2')
    def EXP3(self):
        self.update_display('^3')
    def FACT(self):
        self.update_display('!')
    def LN(self):
        self.update_display('ln')
    def LOG(self):
        self.update_display('log')
    
    #Función encargada de modificar el contenido del label
    def update_display(self, text):
     operacion = self.Display.text()
     new = operacion + text
     self.Display.setText(new)
    #Función encargada del limpiar el contenido del label
    def AC(self):
        self.Display.setText('')
    #Función encargada de eliminar contenido del label
    def DEL(self):
        operacion = self.Display.text()
        self.Display.setText(operacion[:-1])
    #Función encargada de cerrar la ejecución
    def OFF(self):
        self.close()
    #Función encargada de brindar el resultado de la operación inscrita en el label
    def RESULTADO(self):
        try:
           result = eval(self.Display.text().replace('^', '**').replace('ln', 'math.log').replace('log', 'math.log10'))
           self.Display.setText(str(result))
        except Exception as e:
           self.Display.setText("¡Error!")
    
    def retranslateUi(self, Calculadora):
        _translate = QtCore.QCoreApplication.translate
        Calculadora.setWindowTitle(_translate("Calculadora", "Calculadora"))
        self.Marca.setText(_translate("Calculadora", "APOLO"))
        self.Modelo.setText(_translate("Calculadora", "FX-2001"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculadora = QtWidgets.QWidget()
    ui = Ui_Calculadora()
    ui.setupUi(Calculadora)
    Calculadora.show()
    sys.exit(app.exec_())
